name: Backport
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Backport Branch
        run: |
          BACKPORT_BRANCH=backport/$(date +'%Y%m%d-%H%M%S')
          echo "BACKPORT_BRANCH=$BACKPORT_BRANCH" >> $GITHUB_ENV
          git checkout main && git checkout -b $BACKPORT_BRANCH
          git push origin $BACKPORT_BRANCH

      - name: Create Pull Request
        run: |
          gh pr create --title "Backport changes to develop: ${{ env.BACKPORT_BRANCH }}" --body "This PR backports changes from `main` to `develop`." --base develop --head ${{ env.BACKPORT_BRANCH }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}